image: node:16.15-alpine

stages:
  - test
  - build
  - deploy

variables:
  POSTGRES_DB: badproject
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  SERVER_HOST: 52.76.109.40
  SERVER_USER: badproject
  
test: 
  stage: test  
  services:
    - postgres:14.3-alpine
  artifacts:
    paths:
      - node_modules
  before_script:    
    - npm install  
  script:
    - npx jest --runInBand --forceExit

build:
  stage: build
  dependencies:
    - test
  artifacts:
    paths:
      - dist
  before_script:
    # - npm install typescript
  script:
    - npx tsc -p .

deploy:
  stage: deploy
  only:
    - production
  image: ubuntu:22.04
  dependencies:
    - build
  before_script:
    - apt update
    - apt install --yes git openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_HOST > ~/.ssh/known_hosts
    - echo "Host aws-setup
            Hostname $SERVER_HOST
            User $SERVER_USER
            IdentityFile ~/.ssh/id_rsa" > ~/.ssh/config
    
  script:
    - echo "commit_hash = $CI_COMMIT_SHA"
    - cat ~/.ssh/config
    - ssh aws-setup "
        git fetch &&\
        git checkout $CI_COMMIT_SHA &&\
        npm install --prod &&\
        cd dist &&\
        npx knex migrate:latest &&\
        pm2 reload ./server.js
        "