image: node:16.15-alpine

stages:
  - test
  - build
  - deploy

variables:
  POSTGRES_DB: badproject
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  
test: 
  stage: test  
  services:
    - postgres:14.3-alpine
  artifacts:
    paths:
      - node_modules
  before_script:    
    - npm install  
  script:
    - npx jest --runInBand --forceExit

build:
  stage: build
  dependencies:
    - test
  artifacts:
    paths:
      - dist
  before_script:
    # - npm install typescript
  script:
    - npx tsc -p .

deploy:
  stage: deploy
  only:
    - production
  image: ubuntu:22.04
  dependencies:
    - build
  before_script:
    - apt update
    - apt install --yes git openssh-client
  script:
    - echo "commit_hash = $CI_COMMIT_SHA"
    - ssh badproject "
        git fetch &&\
        git checkout $CI_COMMIT_SHA &&\
        npm install --prod &&\
        cd dist &&\
        npx knex migrate:latest &&\
        pm2 reload ./server.js
        "