image: node:16.15-alpine

stages:
  - test
  - build

variables:
  POSTGRES_DB: badproject
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  

test: 
  stage: test  
  services:
    - postgres:14.3-alpine
  artifacts:
    paths:
      - emoji-mama/node_modules
  before_script:    
    - npm install  
  script:
    - npx jest --runInBand --forceExit

build:
  stage: build
  dependencies:
    - test
  before_script:
    # - npm install typescript
  script:
    - npx tsc -p .