image: node:16.15-alpine

stages:
  - test
  - build

test: 
  stage: test  
  service:
    - postgres: 14.3-alpine
  before_script:
    - npm install  
  script:
    - npx jest --runInBand --forceExit

build:
  stage: build
  script:
    - npx tsc -p